services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: recipe-app-frontend
    container_name: recipe-app-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: recipe-app-backend
    container_name: recipe-app-backend
    ports:
      - "3001:3001"
    volumes:
      - ./db:/app/db
    env_file:
      - .env