version: "3.8"

services:
  app:
    build: .
    image: recipe-app
    container_name: recipe-app
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env